
BEAMNG_SIM_NAME = 'beamng'
DONKEY_SIM_NAME = 'donkey'
UDACITY_SIM_NAME = 'udacity'
MOCK_SIM_NAME = 'mock'
DAVE2_NAME = "dave2"
CHAUFFEUR_NAME = "chauffeur"
EPOCH_NAME = "epoch"

TEST_SPLIT_BEAMNG = 0.2
TEST_SPLIT_DONKEY = 0.2
TEST_SPLIT_UDACITY = 0.1

SIMULATOR_NAMES = [BEAMNG_SIM_NAME, DONKEY_SIM_NAME, UDACITY_SIM_NAME, MOCK_SIM_NAME]
MODEL_NAMES = [DAVE2_NAME, CHAUFFEUR_NAME, EPOCH_NAME]
AGENT_TYPE_RANDOM = "random"
AGENT_TYPE_SUPERVISED = "supervised"
AGENT_TYPE_AUTOPILOT = "autopilot"
AGENT_TYPES = [AGENT_TYPE_RANDOM, AGENT_TYPE_SUPERVISED, AGENT_TYPE_AUTOPILOT]
TEST_GENERATORS = ["random", "sin"]

ROAD_WIDTH = 8.0
NUM_CONTROL_NODES = 8
NUM_SAMPLED_POINTS = 20
MAX_ANGLE = 270
MIN_ANGLE = 20
SEG_LENGTH = 25

MAX_EPISODE_STEPS = 2000
MAX_EPISODE_STEPS_UDACITY = 500

IMAGE_HEIGHT, IMAGE_WIDTH, IMAGE_CHANNELS = 160, 320, 3
INPUT_SHAPE = (IMAGE_HEIGHT, IMAGE_WIDTH, IMAGE_CHANNELS)
