BEAMNG_SIM_NAME = "beamng"
DONKEY_SIM_NAME = "donkey"
UDACITY_SIM_NAME = "udacity"
MOCK_SIM_NAME = "mock"

SIMULATOR_NAMES = [BEAMNG_SIM_NAME, DONKEY_SIM_NAME, UDACITY_SIM_NAME, MOCK_SIM_NAME]
AGENT_TYPE_RANDOM = "random"
AGENT_TYPE_SUPERVISED = "supervised"
AGENT_TYPE_AUTOPILOT = "autopilot"
AGENT_TYPES = [AGENT_TYPE_RANDOM, AGENT_TYPE_SUPERVISED, AGENT_TYPE_AUTOPILOT]
TEST_GENERATORS = ["random", "sin"]

ROAD_WIDTH = 8.0
NUM_CONTROL_NODES = 8
NUM_SAMPLED_POINTS = 20
MAX_ANGLE = 270
MIN_ANGLE = 20
SEG_LENGTH = 25

MAX_EPISODE_STEPS = 2000

IMAGE_HEIGHT, IMAGE_WIDTH, IMAGE_CHANNELS = 160, 320, 3
INPUT_SHAPE = (IMAGE_HEIGHT, IMAGE_WIDTH, IMAGE_CHANNELS)
