STD_STEERING_ANGLE_FEATURE_NAME = "std_steering_angle"
OLD_STD_STEERING_ANGLE_FEATURE_NAME = "steering_angle"
CURVATURE_FEATURE_NAME = "curvature"
TURNS_COUNT_FEATURE_NAME = "turns_count"
FEATURE_COMBINATIONS = [
    "{}-{}".format(STD_STEERING_ANGLE_FEATURE_NAME, CURVATURE_FEATURE_NAME),
    "{}-{}".format(TURNS_COUNT_FEATURE_NAME, CURVATURE_FEATURE_NAME),
]

STD_STEERING_ANGLE_METRIC = "std_steering_angles"
STD_LATERAL_POSITION_METRIC = "std_lateral_positions"
STD_SPEED_METRIC = "std_speeds"
MAX_LATERAL_POSITION_METRIC = "max_lateral_positions"
QUALITY_METRICS_NAMES = [
    STD_STEERING_ANGLE_METRIC,
    STD_LATERAL_POSITION_METRIC,
    STD_SPEED_METRIC,
    MAX_LATERAL_POSITION_METRIC,
]
